[package]
name = "unship-desktop"
version = "0.1.0"
description = "Unship desktop app"
authors = ["mbenhard"]
edition = "2024"
default-run = "unship-desktop"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
unship-core = { path = "../../../crates/unship-core" }
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "6"
glob = { workspace = true }
notify = "8.2"
base64 = "0.22"

[dev-dependencies]
tempfile = { workspace = true }

[features]
custom-protocol = ["tauri/custom-protocol"]
