/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    privacy: Privacy;
    support: Support;
    philosophy: Philosophy;
    'tech-stack': TechStack;
    download: Download;
    'site-settings': SiteSetting;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    privacy: PrivacySelect<false> | PrivacySelect<true>;
    support: SupportSelect<false> | SupportSelect<true>;
    philosophy: PhilosophySelect<false> | PhilosophySelect<true>;
    'tech-stack': TechStackSelect<false> | TechStackSelect<true>;
    download: DownloadSelect<false> | DownloadSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe this image for accessibility and SEO
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Hero section and numbered content sections for the landing page
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    /**
     * Main headline displayed in the hero area
     */
    title: string;
    /**
     * Supporting text below the title
     */
    subtitle: string;
    /**
     * Short tagline shown below the CTAs (e.g. "Free · MIT Licensed · macOS only")
     */
    tagline?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaLink?: string | null;
  };
  /**
   * Numbered sections displayed below the hero
   */
  sections?:
    | {
        /**
         * e.g. "01"
         */
        number: string;
        /**
         * URL anchor (e.g. "inbox")
         */
        sectionId: string;
        heading: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy policy page content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy".
 */
export interface Privacy {
  id: number;
  pageHeader?: {
    /**
     * Main heading on the privacy page
     */
    pageTitle?: string | null;
    /**
     * Subheading below the title
     */
    pageSubtitle?: string | null;
  };
  /**
   * Each item is a labeled section of the privacy policy
   */
  items?:
    | {
        /**
         * Section heading (e.g. "Your data", "Telemetry")
         */
        label: string;
        /**
         * Explanation text for this section
         */
        detail: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Support page content, contact channels, and FAQ items
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support".
 */
export interface Support {
  id: number;
  pageHeader?: {
    /**
     * Main heading on the support page
     */
    pageTitle?: string | null;
    /**
     * Subheading below the title
     */
    pageSubtitle?: string | null;
  };
  contactChannels?: {
    contactEmail?: string | null;
    githubIssuesUrl?: string | null;
    xDmUrl?: string | null;
  };
  /**
   * Frequently asked questions shown on the support page
   */
  faqItems?:
    | {
        /**
         * URL hash for deep linking (e.g. "gatekeeper")
         */
        anchorId?: string | null;
        question: string;
        /**
         * Plain text answer. Use "Answer HTML" below for formatted content.
         */
        answer?: string | null;
        /**
         * HTML-formatted answer. Overrides plain text answer when present.
         */
        answerHtml?: string | null;
        /**
         * Terminal command displayed in a code block
         */
        code?: string | null;
        /**
         * Additional context shown below the answer
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Philosophy section — design principles and values
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "philosophy".
 */
export interface Philosophy {
  id: number;
  /**
   * e.g. "06"
   */
  sectionNumber?: string | null;
  sectionHeading?: string | null;
  /**
   * Intro text shown above the principles list
   */
  sectionDescription?: string | null;
  /**
   * Core design principles displayed as a list
   */
  principles?:
    | {
        /**
         * Short principle name (e.g. "Local-first")
         */
        label: string;
        /**
         * Explanation of this principle
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Tech stack section — tools and libraries used
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack".
 */
export interface TechStack {
  id: number;
  /**
   * e.g. "07"
   */
  sectionNumber?: string | null;
  sectionHeading?: string | null;
  /**
   * Intro text shown above the tech stack list
   */
  sectionDescription?: string | null;
  /**
   * Technology stack entries displayed as label-value pairs
   */
  items?:
    | {
        /**
         * Category (e.g. "Runtime")
         */
        label: string;
        /**
         * Technology (e.g. "Electron + React")
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Download section content and install commands
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download".
 */
export interface Download {
  id: number;
  /**
   * Main heading for the download section
   */
  heading?: string | null;
  /**
   * Supporting text below the heading
   */
  subheading?: string | null;
  /**
   * The `brew install` command users will copy
   */
  brewCommand?: string | null;
  /**
   * Gatekeeper bypass command for direct downloads
   */
  xattrCommand?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global site configuration, SEO defaults, and analytics
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Used in the footer and browser tab
   */
  siteName: string;
  /**
   * Production URL (e.g. https://unta.sk)
   */
  siteUrl: string;
  /**
   * Displayed in the footer (e.g. v0.1.15)
   */
  version?: string | null;
  /**
   * Link to the source repository
   */
  githubRepo?: string | null;
  /**
   * Fallback <title> when pages don't specify one
   */
  defaultTitle?: string | null;
  /**
   * Fallback meta description for SEO
   */
  defaultDescription?: string | null;
  /**
   * Default social sharing image (1200x630 recommended)
   */
  ogImage?: (number | null) | Media;
  /**
   * Measurement ID (e.g. G-XXXXXXXXXX)
   */
  googleAnalyticsId?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Footer navigation links and sign-off
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Links shown in the footer navigation
   */
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The closing message in the footer
   */
  signoff?: {
    /**
     * e.g. "Love from"
     */
    signoffText?: string | null;
    /**
     * e.g. "Marcus"
     */
    signoffName?: string | null;
    signoffLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        tagline?: T;
        ctaText?: T;
        ctaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
      };
  sections?:
    | T
    | {
        number?: T;
        sectionId?: T;
        heading?: T;
        description?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "privacy_select".
 */
export interface PrivacySelect<T extends boolean = true> {
  pageHeader?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
      };
  items?:
    | T
    | {
        label?: T;
        detail?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support_select".
 */
export interface SupportSelect<T extends boolean = true> {
  pageHeader?:
    | T
    | {
        pageTitle?: T;
        pageSubtitle?: T;
      };
  contactChannels?:
    | T
    | {
        contactEmail?: T;
        githubIssuesUrl?: T;
        xDmUrl?: T;
      };
  faqItems?:
    | T
    | {
        anchorId?: T;
        question?: T;
        answer?: T;
        answerHtml?: T;
        code?: T;
        note?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "philosophy_select".
 */
export interface PhilosophySelect<T extends boolean = true> {
  sectionNumber?: T;
  sectionHeading?: T;
  sectionDescription?: T;
  principles?:
    | T
    | {
        label?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tech-stack_select".
 */
export interface TechStackSelect<T extends boolean = true> {
  sectionNumber?: T;
  sectionHeading?: T;
  sectionDescription?: T;
  items?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "download_select".
 */
export interface DownloadSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  brewCommand?: T;
  xattrCommand?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteUrl?: T;
  version?: T;
  githubRepo?: T;
  defaultTitle?: T;
  defaultDescription?: T;
  ogImage?: T;
  googleAnalyticsId?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  signoff?:
    | T
    | {
        signoffText?: T;
        signoffName?: T;
        signoffLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}